name = "ripple-worker"
main = "src/index.ts"
compatibility_date = "2024-03-25"

[[kv_namespaces]]
binding = "RIPPLE_KV"
id = "fe0289951cd44ccbb3a9e28a888f826f"
preview_id = "fe0289951cd44ccbb3a9e28a888f826f"
